"""empty message

Revision ID: 26c6484b38d9
Revises: 
Create Date: 2019-09-09 01:46:07.451471

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '26c6484b38d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('participants', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.drop_column('participants', 'created_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('participants', 'updated_on')
    op.drop_column('participants', 'created_on')
    # ### end Alembic commands ###
