"""empty message

Revision ID: 2d997e8055f9
Revises: 51273a2c7096
Create Date: 2019-09-01 14:11:31.293258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d997e8055f9'
down_revision = '51273a2c7096'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('single', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'single')
    # ### end Alembic commands ###
