"""empty message

Revision ID: 51273a2c7096
Revises: d6730d12a0d1
Create Date: 2019-08-31 11:18:00.287860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51273a2c7096'
down_revision = 'd6730d12a0d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('payments', sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'updated_on')
    op.drop_column('payments', 'created_on')
    # ### end Alembic commands ###
